### PR TITLE
LP-17 : Fixed issue where the wrong coordinates were being measured w…

### PR DESCRIPTION
**Pull request by AaronDCole**
…hen crossing the date line

### CODE REVIEW

**Comment by craigstanton** [comment]
The maths is wrong. This is why we need tests. if outLat > 180 you should not reduce it by 180, that would convert 181° to 1°

**Comment by AaronDCole** [comment]
Tests don’t help if your logic is wrong in the first place though, hence why I reviewed it with Petula last night and then put it into review to be checked by someone who understands it better then I do :P

We can review it together when I get in, then I will write a test for it.

**Comment by AaronDCole** [comment]
> The maths is wrong. This is why we need tests. if outLat > 180 you should not reduce it by 180, that would convert 181° to 1°

Please review

**Comment by craigstanton** [comment]
I managed to get 194° by clicking to the far right.  

Here's the additional logging code I added and the screenshot of the output is in LP-17

 public adjustLongitude = (longitude: number): number => {
        while (longitude < -180) {

            console.log("increasing longitude by 360 ", longitude);
            longitude = longitude + 360;
        }
        console.log("longitude = ", longitude);
        return longitude;
    }

**Review by craigstanton — APPROVED** [review]

**Pull request merged**
